# Generated by Django 3.1.2 on 2020-10-26 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='single_translations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
