# Generated by Django 3.1.2 on 2020-10-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_failedtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
