# Generated by Django 3.1.2 on 2020-10-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0004_translation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedtranslation',
            name='single_word',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
