# Generated by Django 3.1.2 on 2020-10-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0005_failedtranslation_single_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='single_translations_count',
            new_name='translations_count',
        ),
    ]
