# Generated by Django 3.1.2 on 2020-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0008_translation_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='user_age',
        ),
        migrations.AddField(
            model_name='wordtranslated',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
    ]
